[window]
opacity = 0.95

[font]
size = 11.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#0f2235'
foreground = '#c4cbd4'
dim_foreground = '#8b9298'
bright_foreground = '#e0e6ec'

[colors.cursor]
text = '#0f2235'
cursor = '#53cafa'

[colors.vi_mode_cursor]
text = '#0f2235'
cursor = '#65acff'

[colors.search.matches]
foreground = '#0f2235'
background = '#53cafa'

[colors.search.focused_match]
foreground = '#0f2235'
background = '#00cc66'

[colors.hints.start]
foreground = '#0f2235'
background = '#ffcc00'

[colors.hints.end]
foreground = '#ffcc00'
background = '#268bd2'

[colors.selection]
text = '#0f2235'
background = '#53cafa'

[colors.normal]
black = '#2d3436'
red = '#ff3838'
green = '#00ff7f'
yellow = '#ffb142'
blue = '#00aaff'
magenta = '#ff49ff'
cyan = '#00fff7'
white = '#ffffff'

[colors.bright]
black = '#636e72'
red = '#ff6b6b'
green = '#55efc4'
yellow = '#ffeaa7'
blue = '#74b9ff'
magenta = '#fd79a8'
cyan = '#81ecec'
white = '#ffffff'

[colors.dim]
black = '#151d24'
red = '#9b2c2c'
green = '#00a854'
yellow = '#d4a017'
blue = '#1a5276'
magenta = '#b34792'
cyan = '#008b8b'
white = '#8b9298'


