[window]
opacity = 1.0

[font]
size = 11.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#ffffff'
foreground = '#24292f'
dim_foreground = '#6e7781'
bright_foreground = '#24292f'

[colors.cursor]
text = '#ffffff'
cursor = '#0969da'

[colors.vi_mode_cursor]
text = '#ffffff'
cursor = '#0969da'

[colors.search.matches]
foreground = '#ffffff'
background = '#0969da'

[colors.search.focused_match]
foreground = '#ffffff'
background = '#1a7f37'

[colors.hints.start]
foreground = '#ffffff'
background = '#bf8700'

[colors.hints.end]
foreground = '#ffffff'
background = '#0969da'

[colors.selection]
text = '#ffffff'
background = '#0969da'

[colors.normal]
black = '#24292f'
red = '#cf222e'
green = '#1a7f37'
yellow = '#9a6700'
blue = '#0969da'
magenta = '#8250df'
cyan = '#0550ae'
white = '#eaeef2'

[colors.bright]
black = '#636c76'
red = '#ff8182'
green = '#3fb950'
yellow = '#d4a72c'
blue = '#4493f8'
magenta = '#a371f7'
cyan = '#0969da'
white = '#ffffff'

[colors.dim]
black = '#d8dee4'
red = '#f85149'
green = '#56d364'
yellow = '#e3b341'
blue = '#58a6ff'
magenta = '#a371f7'
cyan = '#79c0ff'
white = '#8b949e'
