# i3status configuration file.
# Editado para mayor claridad, estética y funcionalidad.

general {
    colors = true
    interval = 5
    color_good = "#2AA198"
    color_bad = "#586E75"
    color_degraded = "#DC322F"
    output_format = "i3bar"
}

# Orden de los módulos (ajusta a tu gusto)
order += "cpu_usage"
order += "memory"
order += "disk /"
order += "wireless _first_"
order += "battery all"
order += "volume master"
order += "tztime local"

# CPU USAGE
cpu_usage {
    format = "   CPU: %usage "
}

# MEMORY
memory {
    format = " 󰍛  Used: %used    Free: %available "
    threshold_degraded = "1G"
    format_degraded = "󰍛  Low RAM: %available"
}

# DISK ROOT
disk "/" {
    format = " 󰋊  %avail "
}

# WIRELESS
wireless _first_ {
    format_up = " 󰢾  %essid %ip "
    format_down = " 󰞃  No WiFi "
}

# BATTERY
battery all {
    format = " %status %percentage 󱐋 %remaining "
    format_down = "   No battery"
    last_full_capacity = true
    integer_battery_capacity = true
    status_chr = "⚡"
    status_bat = ""
    status_unk = "?"
    status_full = ""
    low_threshold = 15
    threshold_type = time
}

# VOLUME
volume master {
    format = " 󰕾  %volume "
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

# FECHA Y HORA
tztime local {
    format = "   %d/%m/%y    %H:%M:%S "
}
