# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

theme = "default"

# Terminales
"alacritty" = " "
"xfce4-terminal" = " "
"gnome-terminal" = " "
"konsole" = " "
"tilix" = " "
"terminator" = " "
"kitty" = ""

# Editores y desarrollo
"nvim" = " "
"neovim" = " "
"vim" = " "
"emacs" = ""
"code" = "󰨞 "
"vscode" = "󰨞 "
"sublime_text" = ""
"atom" = ""
"geany" = ""
"jetbrains-studio" = "󰀴"
"pycharm" = ""
"intellij" = ""
"eclipse" = ""
"android-studio" = ""
"arduino" = ""
"docker" = "󰡨"
"git" = ""
"github" = " "
"gitlab" = " "
"rust" = ""
"java" = ""
"python" = ""
"node" = ""
"react" = ""
"typescript" = ""
"html" = ""
"css" = ""
"c++" = ""
"c" = ""
"go" = ""
"php" = ""
"ruby" = ""
"perl" = ""
"lua" = ""
"bash" = ""

# Navegadores
"firefox" = " "
"chrome" = " "
"chromium" = " "
"opera" = " "
"brave" = ""
"vivaldi" = ""
"microsoft-edge" = "󰇩"
"midori" = ""
"epiphany" = ""
"private browsing" = ""
"youtube" = "󰗃"
"google" = ""
"duckduckgo" = ""

# Comunicación
"telegram" = " "
"whatsdesk" = ""
"whatsapp" = ""
"discord" = "󰙯"
"slack" = ""
"skype" = ""
"signal" = "󰍡"
"teams" = "󰊻"
"zoom" = ""
"geary" = " "
"thunderbird" = ""

# Multimedia
"vlc" = "󰕼"
"mpv" = " "
"music" = ""
"spotify" = "󰓇 "
"audacious" = ""
"rhythmbox" = ""
"clementine" = ""
"smplayer" = ""
"gimp" = ""
"inkscape" = ""
"blender" = ""
"obs" = ""
"cheese" = ""
"shotwell" = ""
"pinta" = ""
"krita" = ""
"videostream" = ""

# Utilidades y sistema
"file manager" = " "
"pcmanfm" = " "
"thunar" = " "
"nautilus" = " "
"dolphin" = " "
"nemo" = " "
"libreoffice" = ""
"libreoffice calc" = " "
"libreoffice writer" = ""
"libreoffice impress" = ""
"org.gnome.Software" = "󰊬"
"gthumb" = " "
"menu" = " "
"calculator" = ""
"transmission" = " "
"qbittorrent" = " "
"disk usage" = ""
".pdf" = ""
"evince" = ""
"okular" = ""
"mousepad" = "󰎞"
"blueman-manager" = "󰥰"
"file-roller" = ""
"kvantum" = "󰰊"
"vmware" = ""
"virtualbox" = ""
"genymotion" = "󰓷"
"pa-applet" = "󰕾"
"system monitor" = ""
"htop" = ""
"gnome-system-monitor" = ""
"settings" = ""
"preferences" = ""
"lock" = ""
"power" = "⏻"
"terminal" = " "

# Juegos
"steam" = ""
"lutris" = ""
"retroarch" = ""
"minecraft" = ""
"supertuxkart" = ""

# Otros
"calendar" = ""
"weather" = ""
"notes" = ""
"remmina" = "󰒋"
"remotebox" = "󰒋"
"remmina" = "󰒋"
"remmina" = "󰒋"

[other]
fallback_icon = "🤨"
deduplicate_icons = false
