# Config for workstyle (YAML format)
#
# Format:
# "pattern": "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# Patterns are matched case-insensitively.

theme: default
spotify: "󰓇"
alacritty: ""
Alacritty: ""
Xfce4-terminal: ""
xfce4-terminal: ""
Terminal: ""
github: ""
GitHub: ""
rust: ""
code: "󰨞"
Code: "󰨞"
genymotion: "󰓷"
google: ""
Google-chrome: ""
google-chrome: ""
chrome: ""
Chrome: ""
gitlab: ""
GitLab: ""
private browsing: ""
vlc: "󰕼"
firefox: ""
Firefox: ""
brave: "󰊯"
Brave-browser: "󰊯"
opera: ""
microsoft-edge: "󰇩"
geary: ""
Geary: ""
file manager: ""
pcmanfm: ""
thunar: ""
libreoffice: ""
LibreOffice: ""
neovim: ""
nvim: ""
telegram: ""
org.gnome.Software: "󰊬"
gthumb: ""
menu: ""
calculator: ""
transmission: ""
videostream: ""
mpv: ""
music: ""
disk usage: ""
.pdf: ""
mousepad: "󰎞"
sublime_text: ""
youtube: "󰗃"
youtube music: "󰗃"
blueman-manager: "󰥰"
Blueman-manager: "󰥰"
jetbrains-studio: "󰀴"
react native: ""
docker: "󰡨"
file-roller: ""
kvantum: "󰰊"
vmware: ""
dbeaver: "󰮆"
Spotify: "󰓇"
TelegramDesktop: ""
discord: ""
Discord: ""
Whatsdesk: ""
whatsdesk: ""
Steam: ""
steam: ""
Virt-manager: "󰌀"
virt-manager: "󰌀"
Nitrogen: ""
nitrogen: ""
Pavucontrol: ""
pavucontrol: ""
Gimp: ""
gimp: ""
Inkscape: ""
inkscape: ""
other:
  fallback_icon: "?"
  deduplicate_icons: false
